<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

### <font color="green">1.1 Challenge: Importing our Library</font>

In [1]:
# Let's import numpy
#
import numpy as np

### <font color="green">1.2 Challenge: Creating an Array</font>

In [2]:
# Challenge 1 
# Create an array of five zeros
#
array1 = np.zeros(5)
array1

array([0., 0., 0., 0., 0.])

In [3]:
# Challenge 2
# Create an array of six ones 
#
array2 = np.ones(6)
array2

array([1., 1., 1., 1., 1., 1.])

In [4]:
# Challenge 3
# Create an array of the integers from 10 to 50
#
array3 = np.arange(10, 51)
array3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
# Challenge 4
# Create an array of odd integers from 20 to 60
#
array4 = np.arange(21, 60, 2)
array4

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59])

In [8]:
# Challenge 5
# Create an array of 25 random numbers 
#
array5 = np.random.randint(0, 1000, 25)
array5

array([493,  93,  90,  96, 883, 393, 538, 113, 598, 244,  79,   4, 351,
       377, 239, 309, 161,  65, 937, 618, 477, 635, 576, 392, 467])

### <font color="green">1.3 Working with Matrices</font>

In [11]:
# Challenge 6
# Write code to replicate the expected matrix output 
# of the cell shown below
# 
array6 = np.arange(1, 21). reshape(5, 4)
print(array6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
# Challenge 6: Expected Output
# [Do not run this cell]
# The output of this cell will disappear when run

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
# Challenge 7
# Let's write code to replicate the expected matrix output 
# of the cell shown below
# 
print(array6[3:, 1:])   #slicing with double bracket notation

[[14 15 16]
 [18 19 20]]


In [ ]:
# Challenge 7: Expected Output
# [Do not run this cell]
# Running this cell will cause the output below to disappear

[[14 15 16]
 [18 19 20]]


In [ ]:
# Challenge 8
# Let's write code to replicate the expected matrix output 
# of the cell shown below
# 
print(array6[4, 3]) #integer indexing with double bracket notation

20


In [ ]:
# Challenge 8: Expected Output
# [Do not run this cell]
# Running this cell will cause the output below to disappear

20

In [16]:
# Challenge 9
# Let's write code to replicate the expected matrix output 
# of the cell shown below
#
print(array6[3:, :])

[[13 14 15 16]
 [17 18 19 20]]


In [ ]:
# Challenge 9: Expected Output
# [Do not run this cell]
# Running this cell will cause the output below to disappear

[[13 14 15 16]
 [17 18 19 20]]


In [33]:
# Challenge 10
# Let's find out the mean of first column values 
# in our matrix in challenge 6 above
# NOTE: DOUBLE BRACKETING NOTATION- [slice][slice]-FOR THIS GIVES UNDEFINED BEHAVIOUR- AVOID IT, USE SINGLE- [slice, slice]
array7 = array6[0:5,0:1]
print(array7)
print('\n')
print("The mean of the values of the first column is:", np.mean(array7))    #universal array function for mean


[[ 1]
 [ 5]
 [ 9]
 [13]
 [17]]


The mean of the values of the first column is: 9.0


In [30]:
# Challenge 11
# Let's find out the sum of second column values 
# in our matrix in challenge 6 above
#
array8 = array6[0:, 1:2]
print(array8)
print('\n')
print("The sum of the values of the first column is:", np.sum(array8))

[[ 2]
 [ 6]
 [10]
 [14]
 [18]]


The sum of the values of the first column is: 50


In [ ]:
# Challenge 12
# How do we find out the sum of all columns of the challenge 6 output
# The resulting array should contain the sums of each column
# 
print(np.sum(array6, axis = 0)) # 0 is for columns, 1 for rows

[45 50 55 60]
