<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

# Python Programming - Numpy Basics

## 1.0 Importing our Library

In [1]:
# We will first import the numpy library, so that we can leverage external functionalities 
# that do not come with python
# 
import numpy as np

## 1.1 Creating Arrays

In [2]:
# Example 1
# Numpy arrays are a type of data structures that hold some benefits over 
# Python lists such as being more compact, faster access in reading 
# and writing items. To get started, we can create a 1 dimension (1D) Array 
# using a Python List as shown below.
#
my_list = [0, 1, 2, 3, 4]
npy_my_list = np.array(my_list)

print(npy_my_list)

[0 1 2 3 4]


In [3]:
# Example 2
# We can also create 1D arrays of zeros and 2D arrays of ones 
# from Numpy builtin functions by;
#
zeros_arr = np.zeros(5)
ones_arr = np.ones([3, 4])

print(zeros_arr)
print(ones_arr)

[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
# Example 3
# Creating an Array with 3 random values  
# 
rand_arr = np.random.rand(3)

print(rand_arr)

[0.85848254 0.00230539 0.27714876]


In [4]:
# Example 4
# Creating an array with evenly spaced values within a given interval 
# as shown using the Numpy arrange function
# 
even_arr = np.arange(0,6,2)

print(even_arr)

[0 2 4]


In [ ]:
# Example 5
# Create a 5 x 5 matix with elements from 1 to 25
#
five_matrix = np.arange(1,26).reshape(5,5)

print(five_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### <font color="green">1.1 Challenges

In [ ]:
# Challenge 1
# Create a 2D array matix using the list, my_mat = [[0,1,2],[3,4,5]]
# Hint: Learn from Example 1
# 

my_mat = [[0, 1, 2], [3, 4, 5]]
np.array(my_mat)

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
# Challenge 2
# Create a 2D array of zeros 
# Hint: Learn from Example 2
#

np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# Challenge 3
# Create a 2D array of random values
# Hint: Learn from Example 3
# values 0-1

np.random.rand(4).reshape(2, 2)

array([[0.7106306 , 0.41553944],
       [0.99770326, 0.02298505]])

In [13]:
# random values within certain values, not restricted to 0-1
np.random.randint(10, 100, 10).reshape(5, 2)

array([[40, 68],
       [85, 73],
       [81, 89],
       [93, 13],
       [63, 47]])

In [15]:
# Challenge 4
# Create a 3D array with values starting 6, stops at 40 with interval of 2
#

np.arange(6, 41, 2)

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38,
       40])

## 1.2 Attributes and Functions

In [16]:
# We use attributes to access information about a particular array,
# while functions to perform a certain operations to the array. 
# We will learn about attributes and functions in this section of the session.
# First let's generate a 1D array to work with; we will name 
# this attribute attribute_arr as shown below;
# 
attribute_arr = np.random.rand(5)

print(attribute_arr)

[0.61204777 0.69953155 0.91421459 0.87860032 0.25582669]


In [17]:
# Example 1
# Using the max() function
# 
attribute_arr.max()

np.float64(0.9142145890621248)

In [18]:
# Example 2
# Using the min() function 
# 
attribute_arr.min()

np.float64(0.25582668661170493)

In [19]:
# Example 3
# Using the argmax() function to return the indice of the max element of the array 
#
attribute_arr.argmax()

np.int64(2)

In [20]:
# Example 4
# Using the argmin() function to return the indice of the min element of the array
#
attribute_arr.argmin()

np.int64(4)

In [21]:
# Example 5
# Using the shape attribute to find the size of the array
#
attribute_arr.shape

(5,)

### <font color="green">1.2. Challenges</font>

In [25]:
# First generate a 2D array to work with
array1 = np.random.randint(100, 500, 40).reshape(5, 8)
array1

array([[246, 157, 122, 468, 170, 427, 349, 168],
       [430, 298, 245, 223, 187, 236, 276, 356],
       [450, 474, 470, 123, 289, 181, 378, 274],
       [382, 211, 151, 446, 468, 390, 391, 166],
       [254, 290, 408, 432, 338, 209, 388, 334]])

In [26]:
# Challenge 1
# Then we will find the minimum value of the 2D array
#
array1.min()

np.int64(122)

In [27]:
# Challenge 2
# We will find the maximum value of the 2D array
#
array1.max()

np.int64(474)

In [28]:
# Challenge 3
# Then return the indice of the maximun element of the 2D array 
# 
array1.argmax()

np.int64(17)

In [29]:
# Challenge 4
# Again return the indice of the minimum element of the 2D array
# 
array1.argmin()

np.int64(2)

In [32]:
# Challenge 5
# Lastly, return the data type of the generated 2D array using dtype
# 
array1.dtype

dtype('int64')

## 1.3  Indexing  and Broadcasting

In [33]:
# Creating an array to work with. The array will be comprised of even numbers from 0 t0 15
in_array = np.arange(0,15,2)

print(in_array)

[ 0  2  4  6  8 10 12 14]


In [34]:
# Example 1
# Bracketing indexing allows us to access
# elements from a Numpy array as shown
# 
print(in_array[2]) # Displays the third element in the list
print(in_array[1:5]) # Displays values from the second element to the fifth element
print(in_array[3:]) # Displays the 4th element to the last element in the list

4
[2 4 6 8]
[ 6  8 10 12 14]


In [41]:
# Example 2
# Arrays with different sizes cannot be added, subtracted or used in any arithmetic.
# one way of solving this is to duplicate the smaller array so that its size is the same as the larger array.
# This process is called broadasting and is available in numpy. 

# Broadcasting is Numpy's terminology for performing mathematical operations 
# between arrays with different shapes. This example provides insights on 
# broadcasting. First, lets run this cell then later uncomment each block trying
# to understand what happens. 
# Once you're done with the final block, you can get a detailed explanation 
# on broadcasting here: http://bit.ly/NumpyBroadcasting
# 

in_array[0:2] = 100
print(in_array)

# First reseting our array i.e. recreating it
in_array = np.arange(0,11)
print(in_array)

# Then making a copy 
in_array_copy = in_array.copy()
print(in_array_copy)

# Afterwards creating a new array upon slicing
slice_of_arr = in_array[0:5]
print(slice_of_arr)

# Changing the Slice
slice_of_arr[:]=22
print(slice_of_arr)

# NB: Changes also occur in our original array
print(in_array)

# check your copy
print(in_array_copy)

[100 100  22  22  22   5   6   7   8   9  10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[22 22 22 22 22]
[22 22 22 22 22  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [45]:
# Example 3
# Indexing a 2D array (matrices)
# 

ind_arr_2d = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
print(ind_arr_2d)

# Selecting element at row index 1 & column index 2
#
print(ind_arr_2d[1][2])

# Selecting a Row at index 1
#
row = ind_arr_2d[1]
print(row)

# Selecting a column at index 1 
# 
column = ind_arr_2d[:, 1]
print(column)

[[21 22 23]
 [11 22 33]
 [43 77 89]]
33
[11 22 33]
[22 22 77]


In [46]:
# Example 4 
# Fancy Indexing allows us to select entire rows or columns out of order
# as shown
# 

# First creating an array or zeros
arr2d = np.zeros((10,10))
print(arr2d)

# Length of array
arr_length = arr2d.shape[1]
print(arr_length)

# creating the array 
for i in range(arr_length):
    arr2d[i] = i
    
print(arr2d)

# Now selecting the first, third and the fourth rows via fancy indexing
arr2d[[0,2,3]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
10
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

### <font color="green">1.3. Challenges</font>

In [47]:
# First, we create a 2D array to work with
array_2d = np.array(([15,20,25],[15,20,25],[30,35,40]))
array_2d

array([[15, 20, 25],
       [15, 20, 25],
       [30, 35, 40]])

In [48]:
# Challenge 1
# Let's get the 3rd row of the array
# 
array_2d[2][:]

array([30, 35, 40])

In [49]:
# Challenge 2
# Let's get the individual element 35
# using the format arr_2d[row][col] or arr_2d[row,col]
#
array_2d[2, 1]

np.int64(35)

In [52]:
# Challenge 3
# Let's slice the array (2,2) from top right corner

array_2d[0:2, 1:3]

array([[20, 25],
       [20, 25]])

In [58]:
# Challenge 4
# Let's create a random 6 x 4 matrix then select the 3rd and 4th rows
#

array_3d = np.linspace(1, 24, 24).reshape(6, 4)
print(array_3d)

array_3d[3:5][:]

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]
 [21. 22. 23. 24.]]


array([[13., 14., 15., 16.],
       [17., 18., 19., 20.]])

## 1.4 Conditional Selection

In [59]:
# We can use conditions to check for whether elements in a certain range satisfy a condition.
# Let's first creating an array. Do you remember what the arrange function does?
#
conditional_arr = np.arange(1,11)
print(conditional_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [60]:
# Example 1  
# What do we do here?
#
conditional_arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [61]:
# Example 2
# What happens here?
#
bool_arr = conditional_arr > 3
print(bool_arr)

print(conditional_arr[bool_arr])

[False False False  True  True  True  True  True  True  True]
[ 4  5  6  7  8  9 10]


In [62]:
# Example 3
# Finally, let's select those values in our array that satisfy our condition
# 
print(conditional_arr[conditional_arr > 4])

[ 5  6  7  8  9 10]


### <font color="green">1.4 Challenges</font>

In [63]:
# Creating the array to be used below
#
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [65]:
# Challenge 1
# Get the 2nd row using conditional selection
#
a = x[1][:]
a

array([3, 4, 5])

In [ ]:
# Challenge 2
# Which elements are greater than two?
#

# for slice
a[a > 2]

array([3, 4, 5])

In [ ]:
# for matrice
# 
x[x > 2]

array([3, 4, 5, 6, 7, 8])

In [68]:
# Challenge 3
# Get the array [7, 8] from the x array
# 

x[2:, 1:3]

array([[7, 8]])

## 1.5 Operations

In [71]:
# Creating the array that we will use below:
# 
a = np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [74]:
# Example 1
# Arithmetic Operations
# 
addition_arr = a + a
print(addition_arr)

subtraction_arr = a - a
print(subtraction_arr)

[0 2 4 6 8]
[0 0 0 0 0]


In [73]:
# Example 2
# Universal Array Functions
# 

# square root
sqr_arr = np.sqrt(a)
print(sqr_arr)

# exponential
exp_arr = np.exp(a)
print(exp_arr)

[0.         1.         1.41421356 1.73205081 2.        ]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


### <font color="green">1.5 Challenges</font>

In [75]:
# Challenge 1
# Raise the a array created above to the power of 2

square_a = np.square(a)
square_a

array([ 0,  1,  4,  9, 16])

In [76]:
# Challenge 2
# Find the log of a using log(), 
# the Universal Array Functions
#

log_a = np.log(a)
log_a

/tmp/ipykernel_4453/1553866653.py:6: RuntimeWarning: divide by zero encountered in log
  log_a = np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [92]:
# Challenge 3
# Think of a dataset then determine where you can use the 
# numpy concepts that you learnt in this session?
# Then explain them to your peer.

#concepts- creating numpy arrays

#1 - from list
a = [20, 15, 60, 100]
np_a = np.array(a)
print(np_a)
#minimum
print(np_a.min())
#maximum
print(np_a.max())
#index of minimum value
print(np_a.argmin())
#index of maximum value
print(np_a.argmax())

print('\n\n\n')

#2 - create array of 0s
c = np.zeros(5)
print(c)
#shape attribut
print(c.shape)
#size attribute
print(c.size)

print('\n\n\n')

#3- create array of 1s
d = np.ones((4, 3))
print(d)
#reshape
d_reshape = d.reshape(12)
print(d_reshape)

[ 20  15  60 100]
15
100
1
3




[0. 0. 0. 0. 0.]
(5,)
5




[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# 4- range
e = np.arange(100, 50, -5)
print(e)
# slicing
print(e[3:])

print('\n\n\n')

# 5- interval
f = np.linspace(1, 10, 10).reshape(5, 2)
print(f)
# indexing with integer with double bracket notation
print(f[3][1])
#slicing with slices with single bracket notation
print(f[3:, :])
# IMPORTANT: DOUBLE BRACKET NOTATION CAN LEAD TO UNDEFINED BEHAVIOUR
# IMPORTANT 2: WHEN YOU MIX INTEGER INDEXING WITH SLICE INDEXING IT WILL YIELD AN ARRAY OF LOWER RANK

print('\n\n\n')

# 6- random values but from 0-1
g = np.random.random((2, 4))
print(g)
g2 = np.random.randint(1, 10, 8).reshape(4,2)
print(g2)
# Broadcasting so we can add g2 + g
# print(g2 + g)
# Operands can not be added - operands could not be broadcast together with shapes (4,2) (2,4) 
# change shape of g2
g3 = g2.reshape(2, 4)
print(g3 + g)

[100  95  90  85  80  75  70  65  60  55]
[85 80 75 70 65 60 55]




[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]]
8.0
[[ 7.  8.]
 [ 9. 10.]]




[[0.18301789 0.88061674 0.75142208 0.76156341]
 [0.16262976 0.58554054 0.49927147 0.45445158]]
[[3 8]
 [4 5]
 [9 4]
 [6 9]]
[[3.18301789 8.88061674 4.75142208 5.76156341]
 [9.16262976 4.58554054 6.49927147 9.45445158]]


In [113]:
# 6- random values
h = np.random.randint(1, 100, 28).reshape(7, 4)
print(h)
print('\n')
# scalar operations
print(h - 3)

print('\n\n\n')
# matrice multiplication
# For matrice multiplication use dot function or @ operator
# * is for elementwise multiplication which does not apply to matrices

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7], [7, 8, 9]])

# a is 2*2 matrix while b is a 2*3 matrix
# the column of a is the same as the row of b so they can be multiplied
# resulting matrix will be a 2*3 matrix taken from row of a and column of b
print(a @ b)
print('\n')
print(a.dot(b))
print('\n')
print(np.dot(a, b))

[[93 37 93 24]
 [ 7 30 29 58]
 [21 15 97 53]
 [23 90 25 60]
 [34 78 78 85]
 [55 52 73 23]
 [50 83 43 77]]


[[90 34 90 21]
 [ 4 27 26 55]
 [18 12 94 50]
 [20 87 22 57]
 [31 75 75 82]
 [52 49 70 20]
 [47 80 40 74]]




[[19 22 25]
 [43 50 57]]


[[19 22 25]
 [43 50 57]]


[[19 22 25]
 [43 50 57]]


In [117]:
# fancy indexing
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])
# print(a[[0, 1, 2], [0, 1, 0]]) is equivalent to print(a[0, 0], a[1, 1], a[2, 0])
# print(a[[0, 1, 2], [0, 1, 0]]) is fancy indexing
print('\n')
print(np.array((a[0, 0], a[1, 1], a[2, 0])))

[1 4 5]


[1 4 5]
